Neos:
  GoogleAnalytics:
    sites:
      'neosio':
        analytics:
          id: 'UA-57276307-4'
        profileId: '120499365'
      'neosconio':
        analytics:
          id: 'UA-57276307-5'
        profileId: '120499365'
      'flowneosio':
        analytics:
          id: 'UA-57276307-6'
        profileId: '120499365'
